name       : gdl
version    : 3.34.0
release    : 1
source     :
    - https://gitlab.gnome.org/GNOME/gdl/-/archive/GDL_3_34_0/gdl-GDL_3_34_0.tar.gz : 486255bdd848cea1657e41f48b26391b2c2a801b5e46c31e4512f47462c2ee24
license    : GPL-2.0-or-later
component  : programming.library
summary    : Provides docking features for gtk+
description: |
    GDL provides a docking system and several utilities useful to GNOME development tools and GNOME applications in general.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - gnome-common
setup      : |
    %patch -p1 < $pkgfiles/0001-disable-building-gtk-docs.patch
    %autogen
    %configure
build      : |
    %make
install    : |
    %make_install
